search-service:
  config:
    scheme: https
    host: www.avito.ru
    port: 443
    encode: UTF-8
  parser:
    item-table-class: item_table
    item-link-class: item-description-title-link
    item-link-attr: abs:href
    item-date-class: js-item-date
    item-date-attr: data-absolute-date
    item-price-class: price
    item-data-class: data
    item-vip-list-class: vas-list-container
    item-vip-list-attr: data-config
    item-is-upped-prop: isUpped