search-service:
  config:
    scheme: https
    host: www.avito.ru
    port: 443
    encode: UTF-8
    time-out: 10000 #ms
    user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36'
    referer: http://www.google.com
  parser:
    table-class: item_table
    link-class: item-description-title-link
    date-class: js-item-date
    date-attr: data-absolute-date
    price-class: price
    data-class: data
    vip-list-class: vas-list-container
    vip-list-attr: data-config
    is-upped-prop: isUpped
    next-page-class: js-pagination-next
    count-class: page-title-count